when:
  - event: manual
  - event: push
    branch: main

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx:2
    secrets:
      - docker_username
      - docker_password
    settings:
      logins:
        # Default DockerHub login
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
      platforms: linux/amd64,linux/arm64
      repo: teamgosh/caddy
      dockerfile: Dockerfile
      tag: latest
