when:
  - event: manual
  - event: push
    branch: main

variables:
  - &build_plugin "woodpeckerci/plugin-docker-buildx:latest"
  - &CADDY_VERSION "2.8.4"

steps:
  publish:
    image: *build_plugin
    secrets:
      - docker_username
      - docker_password
    settings:
      logins:
        # Default DockerHub login
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
      platforms: linux/amd64,linux/arm64
      repo: teamgosh/caddy
      dockerfile: Dockerfile
      build_args:
        CADDY_VERSION: *CADDY_VERSION
      tags:
        - latest
        - *CADDY_VERSION
